context:
  name: hatch-js
  version: "0.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/hatch_js/hatch_js-${{ version }}.tar.gz
  sha256: 8b2d37944be13bb600ffec8346da272e0b450355e703fef01e3b44c656fbbf95

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - hatchling
    - pydantic

tests:
  - python:
      imports:
        - hatch_js.hooks
        - hatch_js.plugin
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: hatch plugin for javascript
  homepage: https://github.com/python-project-templates/hatch-js
  repository: https://github.com/python-project-templates/hatch-js

extra:
  recipe-maintainers:
    - timkpaine
